URLS = [
    # DK Large cap
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5RL',  # A. P. Moller Maersk A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5RN',  # Ambu
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5RB',  # Bavarian Nordic A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5K1',  # Carlsberg A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000OO3C',  # Chr. Hansen Holding A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5K4',  # Coloplast A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5KA',  # Danske Bank A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5LK',  # Demant AS
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5Q9',  # DSV Panalpina AS
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5RO',  # FLSmidth & Co. A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5QU',  # Genmab A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5KG',  # GN Store Nord A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00012E78',  # ISS A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5KR',  # Jyske Bank A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5Q7',  # Lundbeck A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5BQ',  # Novo Nordisk A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5QX',  # Novozymes A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000Q1VF',  # Pandora A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5L9',  # Rockwool International A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5QC',  # Royal UNIBREW A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5QV',  # SimCorp A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5RI',  # Tryg A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5Q5',  # Vestas Wind Systems A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0001846T',  # Ørsted A/S

    # DK Mid cap
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5LL',  # Alk-Abello A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5PI',  # Alm Brand AS
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5K5',  # DFDS A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0001H6JR',  # Drilling Company of 1972
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5RA',  # Jeudan A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5PB',  # Copenhagen Airports A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0001DFE0',  # Netcompany Group AS
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A6IU',  # Nordea Bank Abp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5L8',  # Ringkjøbing Landbobank A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00017EFW',  # Scandinavian Tobacco Group A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5JU',  # Schouw & Co A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5PV',  # Spar Nord Bank A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5R6',  # Sydbank A/S

    # DK Small cap
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5PC',  # Brødrene Hartmann A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5PK',  # Dampskibsselskabet NORDEN A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000Z26I',  # Matas A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0001BQUO',  # Nilfisk Holding A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5KX',  # NKT A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5QW',  # RTX A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5QR',  # Solar A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5KP',  # SP Group A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0001C9AZ',  # TCM Group A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5LG',  # Topdanmark A/S
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A5QN',  # UIE PLC

    # SE selected by me
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A6N7',  # Note AB
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000A6GI',  # Hennes & Mauritz AB

    # Dow Jones
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000053I',  # The Travelers Company Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0001H3ZI',  # Dow Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005UI',  # Walgreens Boot Alliance Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000014I',  # Caterpillar Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002H5',  # Goldman Sachs Group Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000000I',  # 3M Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000CU',  # American Express Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005NO',  # Raytheon Technologies Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002RH',  # IBM Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003X1',  # Nike Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003IJ',  # McDonald's Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000TU',  # Boeing Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000019Y',  # Cisco Systems Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000185',  # Chevron Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000CHAD',  # Pfizer Ltd
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003KE',  # Merck & Co Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005QY',  # Verizon Communications Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001BW',  # Coca-Cola Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005UJ',  # The Walt Disney Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002OY',  # The Home Depot Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000220',  # Exxon Mobil Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005NU',  # UnitedHealth Group Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002X8',  # Intel Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004GV',  # Procter & Gamble Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005UH',  # Walmart Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000032S',  # Johnson & Johnson
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000031C',  # JPMorgan Chase & Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000CPCP',  # Visa Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000GY',  # Apple Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003MH',  # Microsoft Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000B7',  # Amazon.com Inc

    # US selected by me
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000WX',  # Bunge Ltd
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000TDWC',  # Mosaic Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002DT',  # General Mills Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002HD',  # Alphabet Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000031',  # AT&T Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001HZ',  # Ingredion Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000XPGW',  # AbbVie Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005K5',  # Tyson Foods Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00008WF2',  # B&G Foods Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004B0',  # PepsiCo Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001CL',  # Colgate-Palmolive Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000RD',  # Berkshire Hathaway Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002DN',  # General Dynamics Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001GL',  # Consolidated Edison Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00016CR2',  # The Kraft Heinz Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000AV',  # Altria Group Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001BD',  # Clorox Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002PC',  # Honeywell (HON)
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000K5',  # Assurant (AIZ)
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001IK',  # Costco Wholesale Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005B5',  # Target Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000M76Q',  # Dollar General Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001R5',  # Dollar Tree Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000357',  # Kimberly-Clark Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000019F',  # Church & Dwight Co Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003WA',  # Newell Brands Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000YWYX',  # Coty Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002PP',  # Hormel Foods Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003IF',  # McCormick & Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001FX',  # Conagra Brands Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000034A',  # Kellogg Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000011A',  # Campbell Soup Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000031B',  # JM Smucker Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00018XMP',  # Lamb Weston Holdings Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000CUPM',  # Philip Morris Internation Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000036D',  # Mondelez International Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002NZ',  # The Hershey Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000I0',  # Archer-Daniels Midland Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000059B',  # Sysco Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000036H',  # The Kroger Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000VL',  # Bristol-Myers Squibb Company
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000035Z',  # Kohl's Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003C9',  # Lowe's Companies Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000246',  # Macy's Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000412',  # Occidental Petroleum Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000059E',  # T. Rowe Price Group Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000XYO2',  # Zoetis Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000QR',  # Becton, Dickinson and Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000WD',  # Brown-Forman Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004X6',  # Sherwin-Williams Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000003P',  # Abbott Laboratories
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000004C',  # Accenture PLC Class A
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000056',  # Acuity Brands Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000005M',  # Adobe Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000007E',  # Agilent Technologies Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000CU',  # American Express Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00009JO7',  # American Water Works Co Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000H9',  # Applied Materials Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000LK',  # AutoZone Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000PA',  # Bank of America Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000RH',  # Best Buy Co Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000T6',  # BlackRock Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000KU35',  # Broadcom Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000013F',  # Carnival Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000014I',  # Caterpillar Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000068U',  # Chipotle Mexican Grill Inc Class A
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001A2',  # Citigroup Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001GE',  # ConocoPhillips
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001GT',  # Constellation Brands Inc A
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001HC',  # The Cooper Companies Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000062O',  # eBay Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001W8',  # Electronic Arts Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001WJ',  # Eli Lilly and Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001X9',  # Emerson Electric Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000021X',  # Extra Space Storage Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000023X',  # FedEx Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000029O',  # Forward Industries Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002CM',  # Gap Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002CQ',  # Garmin Ltd
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002DO',  # General Electric Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000RQZL',  # General Motors Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002EG',  # Genuine Parts Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00016V9T',  # Hewlett Packard Enterprise Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002TG',  # Illinois Tool Works Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002YT',  # International Paper Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000SDEF',  # Kinder Morgan Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003AV',  # L Brands Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000039L',  # Leggett & Platt Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003BP',  # Lockheed Martin Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000068W',  # Loews Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00005U6B',  # Mastercard Inc A
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003IF',  # McCormick & Co Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003OO',  # Molson Coors Beverage Co B
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002L4',  # Monster Beverage Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003PN',  # Motorola Solutions Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000003',  # 1-800-Flowers.com Inc Class A
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003UP',  # Netflix Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003WA',  # Newell Brands Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003RE',  # NVIDIA Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000043L',  # Oracle Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000048G',  # Parker Hannifin Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00016CGN',  # PayPal Holdings Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004BB',  # PerkinElmer Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004I8',  # Public Storage
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004J4',  # Qualcomm Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004EB',  # Ralph Lauren Corp Class A
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000007H',  # Agree Realty Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004PK',  # Rockwell Automation Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004UK',  # Schlumberger Ltd
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004VE',  # Seagate Technology PLC
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004VF',  # Sealed Air Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000053X',  # Stanley Black &amp; Decker Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000546',  # Starbucks Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000054E',  # State Street Corporation
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000563',  # Stryker Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005B5',  # Target Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005EI',  # Texas Instruments Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005F1',  # Thermo Fisher Scientific Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005A3',  # TJX Companies Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005H8',  # Tractor Supply Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000UTBL',  # TripAdvisor Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005QH',  # Ventas Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005QP',  # VeriSign Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005TG',  # Vulcan Materials Co
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005V2',  # Waste Management Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005V9',  # Waters Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005XP',  # Whirlpool Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005YA',  # Williams Companies Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000060R',  # Xerox Holdings Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000061H',  # Yum Brands Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000008C',  # Albemarle Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000KX',  # Atmos Energy Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000000LO',  # Automatic Data Processing Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000130',  # Cardinal Health Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000001C',  # Chubb Ltd
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000019F',  # Church &amp; Dwight Co Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000019P',  # Cincinnati Financial Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000019R',  # Cintas Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001RL',  # Dover Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000001V4',  # Ecolab Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000020R',  # Essex Property Trust Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000021P',  # Expeditors International of Washington Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000241',  # Federal Realty Investment Trust
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000002AB',  # Franklin Resources Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004FA',  # Linde PLC
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003C9',  # Lowe's Companies Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003JU',  # Medtronic PLC
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000003ZV',  # Nucor Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000X06P',  # Pentair PLC
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000004B0',  # PepsiCo Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P00000467',  # PPG Industries Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P0000059B',  # Sysco Corp
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005TP',  # W.W. Grainger Inc
    'https://www.morningstar.dk/dk/stockquicktake/default.aspx?id=0P000005WS',  # West Pharmaceutical Services Inc
]
